db-uri = "postgres://authenticator@127.0.0.1:54322/postgres"
db-schemas = "public, olivia_energy"
db-anon-role = "anon"
jwt-secret = "harness-jwt-secret-with-at-least-32-characters"
server-host = "127.0.0.1"
server-port = 3010
db-pool = 10
