/**
 * Builds supabase/hosted-setup.sql: one file that sets up a hosted Supabase
 * project by being pasted into its SQL Editor. It is the migrations plus the
 * content seeds (settings, publications, starter articles) in a single
 * transaction, so it either applies completely or changes nothing.
 *
 *   npm run db:hosted-sql            # rewrite the file
 *   npm run db:hosted-sql -- --check # exit 1 if the file is out of date
 *
 * Why a pasted file rather than `supabase db push`: the project may be
 * shared with other applications, whose migration history `db push` would
 * trip over. Everything here lives in the olivia_energy schema and touches
 * nothing else. supabase/seeds/local-admin.sql is left out on purpose (its
 * password is public); create the first admin with scripts/create-admin.mjs.
 */
import fs from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const supabase = path.join(root, "supabase");
const out = path.join(supabase, "hosted-setup.sql");

const migrations = fs
  .readdirSync(path.join(supabase, "migrations"))
  .filter((name) => name.endsWith(".sql"))
  .sort()
  .map((name) => `migrations/${name}`);
const parts = [
  ...migrations,
  "seed.sql",
  "seeds/publications.sql",
  "seeds/starter-articles.sql",
];

const header = `-- =====================================================================
-- OLIVIA ENERGY — hosted setup. GENERATED by scripts/hosted-sql.mjs from
-- supabase/migrations and the content seeds; edit those and re-run
-- \`npm run db:hosted-sql\`, not this file.
--
-- Use: Supabase dashboard → SQL Editor → New query → paste this whole file
-- → Run. Then Project Settings → Data API → Exposed schemas → add
-- olivia_energy. The last statement prints the row counts.
--
-- Safe on a project shared with other applications: it creates the
-- olivia_energy schema, the olivia-energy-media storage bucket and four
-- policies on storage.objects that apply to that bucket only. It creates,
-- alters, revokes or drops nothing else, and it runs in one transaction:
-- if any statement fails, or the schema already exists, nothing changes.
-- =====================================================================

begin;

do $$
begin
  if exists (select 1 from pg_namespace where nspname = 'olivia_energy') then
    raise exception 'The olivia_energy schema already exists, so this script has already been run. Nothing was changed.';
  end if;
end
$$;
`;

const footer = `
-- Tell the Data API about the new schema's tables.
notify pgrst, 'reload schema';

commit;

select
  (select count(*) from olivia_energy.settings) as settings,
  (select count(*) from olivia_energy.publications) as publications,
  (select count(*) from olivia_energy.posts) as articles,
  (select count(*) from storage.buckets where id = 'olivia-energy-media') as media_bucket;
`;

const body = parts
  .map((name) => {
    const sql = fs.readFileSync(path.join(supabase, name), "utf8").trimEnd();
    return `\n-- >>>>> supabase/${name}\n\n${sql}\n`;
  })
  .join("");
const sql = header + body + footer;

if (process.argv.includes("--check")) {
  const current = fs.existsSync(out) ? fs.readFileSync(out, "utf8") : "";
  if (current !== sql) {
    console.error(
      "supabase/hosted-setup.sql is out of date. Run `npm run db:hosted-sql`.",
    );
    process.exit(1);
  }
  console.log("supabase/hosted-setup.sql is up to date.");
} else {
  fs.writeFileSync(out, sql);
  console.log(
    `Wrote supabase/hosted-setup.sql (${parts.length} files, ${Math.round(sql.length / 1024)} KB).`,
  );
}
